### PR TITLE
Mask cauldron top to match vanilla texture

### PR DESCRIPTION
**Pull request by ScottKillen**
This allows water to be seen when the cauldron is filled. Full texture occludes water.

### CODE REVIEW

**Comment by ScottKillen** [comment]
After:

**Comment by ScottKillen** [comment]
Is anyone reviewing these anymore?

**Comment by ScottKillen** [comment]
@lesdmark Would you mind merging this so I can delete my fork?

I know we aren't really publishing the 1.7.10 pack--but this final annoyance still remains.

Also--I am happy to do this myself if you give me the same permissions I have on the Modded repos.

Thanks!

**Comment by lesdmark** [comment]
Funny thing about that. I had already made that same change to my own personal version ages ago. lol.

**Comment by ScottKillen** [comment]
Thank you!

**Pull request merged**
